module.exports = {
  ROOM_CREATION: 'ROOM_CREATION',
  PLAYER_JOINED: 'PLAYER_JOINED',
  JOIN_GAME: 'JOIN_GAME',
  JOIN_SERVER: 'JOIN_SERVER',
  CREATE_SERVER: 'CREATE_SERVER',
  PLAYER_CONNECTED: 'PLAYER_CONNECTED',
  CLIENT_CONNECTED: 'CLIENT_CONNECTED',
  RECONNECT: 'RECONNECT',
  INIT: 'INIT'
}
