module.exports = {
  ASSIGNED_KING: 'ASSIGNED_KING',
  ASSIGNED_CHARACTER: 'ASSIGNED_CHARACTER',
  KINGS_ASSIGNED_PLAYERS: 'KINGS_ASSIGNED_PLAYERS',
  REQUEST_VOTE_FOR_ASSIGNED_PLAYERS: 'REQUEST_VOTE_FOR_ASSIGNED_PLAYERS',
  VOTE_FOR_ASSIGNED_PLAYERS: 'VOTE_FOR_ASSIGNED_PLAYERS',
  REVEAL_KINGS_ASSIGNED_PLAYERS_VOTE_RESULT: 'REVEAL_KINGS_ASSIGNED_PLAYERS_VOTE_RESULT',
  REQUEST_VOTE_FOR_MISSION: 'REQUEST_VOTE_FOR_MISSION',
  VOTE_FOR_MISSION: 'VOTE_FOR_MISSION',
}
